var c=void 0,f=!0,h=null,j=!1;function k(a){return function(){return this[a]}}function m(a){return function(){return a}}var n,aa=this;aa.hc=f;Math.floor(2147483648*Math.random()).toString(36);function r(a,b){var d=a.split("."),e=aa;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&b!==c?e[g]=b:e=e[g]?e[g]:e[g]={}}function t(a,b){function d(){}d.prototype=b.prototype;a.e=b.prototype;a.prototype=new d;a.prototype.constructor=a}document.createElement("video");
document.createElement("audio");function u(a,b,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.na[a])return u.na[a];a=u.k(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new v(a,b,d)}var ba=u;u.Sa="GENERATED_CDN_VSN";u.Ra="https:"==document.location.protocol?"https://":"http://";
u.options={techOrder:["html5","flash"],html5:{},flash:{tc:u.Ra+"vjs.zencdn.net/c/video-js.swf"},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};u.na={};"GENERATED_CDN_VSN"!=u.Sa&&(ba.options.flash.swf=u.Ra+"vjs.zencdn.net/"+u.Sa+"/video-js.swf");
u.d=function(a,b,d){var e=u.getData(a);e.q||(e.q={});e.q[b]||(e.q[b]=[]);d.o||(d.o=u.o++);e.q[b].push(d);e.I||(e.disabled=j,e.I=function(b){if(!e.disabled){b=u.ab(b);var d=e.q[b.type];if(d)for(var d=d.slice(0),l=0,s=d.length;l<s&&!b.gb();l++)d[l].call(a,b)}});1==e.q[b].length&&(document.addEventListener?a.addEventListener(b,e.I,j):document.attachEvent&&a.attachEvent("on"+b,e.I))};
u.n=function(a,b,d){if(u.fb(a)){var e=u.getData(a);if(e.q)if(b){var g=e.q[b];if(g){if(d){if(d.o)for(e=0;e<g.length;e++)g[e].o===d.o&&g.splice(e--,1)}else e.q[b]=[];u.Va(a,b)}}else for(g in e.q)b=g,e.q[b]=[],u.Va(a,b)}};u.Va=function(a,b){var d=u.getData(a);0===d.q[b].length&&(delete d.q[b],document.removeEventListener?a.removeEventListener(b,d.I,j):document.detachEvent&&a.detachEvent("on"+b,d.I));u.Fa(d.q)&&(delete d.q,delete d.I,delete d.disabled);u.Fa(d)&&u.lb(a)};
u.ab=function(a){function b(){return f}function d(){return j}if(!a||!a.Ga){var e=a||window.event,g;for(g in e)a[g]=e[g];a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){a.returnValue=j;a.ga=b};a.ga=d;a.stopPropagation=function(){a.cancelBubble=f;a.Ga=b};a.Ga=d;a.stopImmediatePropagation=function(){a.gb=b;a.stopPropagation()};a.gb=d;a.clientX!=h&&(e=document.documentElement,g=document.body,a.pageX=a.clientX+(e&&
e.scrollLeft||g&&g.scrollLeft||0)-(e&&e.clientLeft||g&&g.clientLeft||0),a.pageY=a.clientY+(e&&e.scrollTop||g&&g.scrollTop||0)-(e&&e.clientTop||g&&g.clientTop||0));a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.i=function(a,b){var d=u.fb(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof b&&(b={type:b,target:a});b=u.ab(b);d.I&&d.I.call(a,b);if(e&&!b.Ga())u.i(e,b);else if(!e&&!b.ga()&&(d=u.getData(b.target),b.target[b.type])){d.disabled=f;if("function"===typeof b.target[b.type])b.target[b.type]();d.disabled=j}return!b.ga()};u.F=function(a,b,d){u.d(a,b,function(){u.n(a,b,arguments.callee);d.apply(this,arguments)})};
u.c=function(a,b){var d=document.createElement(a||"div"),e;for(e in b)b.hasOwnProperty(e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,b[e]):d[e]=b[e]);return d};u.L=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.g={};u.g.toString=Object.prototype.toString;u.g.hasOwnProperty=Object.prototype.hasOwnProperty;u.g.W=function(a,b,d){for(var e in a)u.g.hasOwnProperty.call(a,e)&&b.call(d||this,e,a[e])};
u.g.u=function(a,b){if(!b)return a;for(var d in b)u.g.hasOwnProperty.call(b,d)&&(a[d]=b[d]);return a};u.g.$a=function(a,b){var d,e,g;a=u.g.copy(a);for(d in b)u.g.hasOwnProperty.call(b,d)&&(e=a[d],g=b[d],a[d]="[object Object]"===u.g.toString.call(e)&&"[object Object]"===u.g.toString.call(g)?u.g.$a(e,g):b[d]);return a};u.g.copy=function(a){return u.g.u({},a)};u.bind=function(a,b,d){function e(){return b.apply(a,arguments)}b.o||(b.o=u.o++);e.o=d?d+"_"+b.o:b.o;return e};u.V={};u.o=1;
u.expando="vdata"+(new Date).getTime();u.getData=function(a){var b=a[u.expando];b||(b=a[u.expando]=u.o++,u.V[b]={});return u.V[b]};u.fb=function(a){a=a[u.expando];return!(!a||u.Fa(u.V[a]))};u.lb=function(a){var b=a[u.expando];if(b){delete u.V[b];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};u.Fa=function(a){for(var b in a)if(a[b]!==h)return j;return f};
u.p=function(a,b){-1==(" "+a.className+" ").indexOf(" "+b+" ")&&(a.className=""===a.className?b:a.className+" "+b)};u.v=function(a,b){if(-1!=a.className.indexOf(b)){var d=a.className.split(" ");d.splice(d.indexOf(b),1);a.className=d.join(" ")}};u.ca=u.c("video");u.B=navigator.userAgent;u.wb=!!u.B.match(/iPhone/i);u.vb=!!u.B.match(/iPad/i);u.xb=!!u.B.match(/iPod/i);u.ub=u.wb||u.vb||u.xb;var ca=u,da;var ea=u.B.match(/OS (\d+)_/i);da=ea&&ea[1]?ea[1]:c;ca.ic=da;u.sb=!!u.B.match(/Android.*AppleWebKit/i);
var fa=u,ga=u.B.match(/Android (\d+)\./i);fa.rb=ga&&ga[1]?ga[1]:h;u.tb=function(){return!!u.B.match("Firefox")};u.Ca=function(a){var b={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,p=d.length-1;0<=p;p--){e=d[p].name;g=d[p].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:j;b[e]=g}return b};
u.oc=function(a,b){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(b):a.currentStyle&&(b=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),d=a.currentStyle[b]);return d};u.Ea=function(a,b){b.firstChild?b.insertBefore(a,b.firstChild):b.appendChild(a)};u.Qa={};u.k=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.fa=function(a,b){b=b||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),p=Math.floor(b/60%60),l=Math.floor(b/3600),g=0<g||0<l?g+":":"";return g+(((g||10<=p)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.Ab=function(){document.body.focus();document.onselectstart=m(j)};u.dc=function(){document.onselectstart=m(f)};u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,b){b||(b=0);return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};
u.Ya=function(a){return{length:1,start:m(0),end:function(){return a}}};
u.get=function(a,b,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(p){d(p)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?b(g.responseText):d&&d())};try{g.send()}catch(l){d&&d(l)}};u.Yb=function(a){var b=window.localStorage||j;if(b)try{b.volume=a}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.eb=function(a){a.match(/^https?:\/\//)||(a=u.c("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Gb="getBoundingClientRect"in document.documentElement?function(a){var b;try{b=a.getBoundingClientRect()}catch(d){}if(!b)return 0;a=document.body;return b.left+(window.pageXOffset||a.scrollLeft)-(document.documentElement.clientLeft||a.clientLeft||0)}:function(a){for(var b=a.offsetLeft;a=a.offsetParent;)b+=a.offsetLeft;return b};
function x(a,b,d){this.b=a;this.f=u.g.copy(this.f);b=this.options(b);this.C=b.id||(b.el&&b.el.id?b.el.id:a.id()+"_component_"+u.o++);this.Lb=b.name||h;this.a=b.el||this.c();this.w=[];this.xa={};this.H={};if((a=this.f)&&a.children){var e=this;u.g.W(a.children,function(a,b){b!==j&&!b.loadEvent&&(e[a]=e.J(a,b))})}y(this,d)}n=x.prototype;
n.z=function(){if(this.w)for(var a=this.w.length-1;0<=a;a--)this.w[a].z&&this.w[a].z();this.H=this.xa=this.w=h;this.n();this.a.parentNode&&this.a.parentNode.removeChild(this.a);u.lb(this.a);this.a=h};n.Sb=k("b");n.options=function(a){return a===c?this.f:this.f=u.g.$a(this.f,a)};n.c=function(a,b){return u.c(a,b)};n.k=k("a");n.id=k("C");n.name=k("Lb");n.children=k("w");
n.J=function(a,b){var d,e;"string"===typeof a?(e=a,b=b||{},d=b.componentClass||u.L(e),b.name=e,d=new window.videojs[d](this.b||this,b)):d=a;this.w.push(d);"function"===typeof d.id&&(this.xa[d.id()]=d);(e=e||d.name&&d.name())&&(this.H[e]=d);"function"===typeof d.el&&d.el()&&this.a.appendChild(d.el());return d};
n.removeChild=function(a){"string"===typeof a&&(a=this.H[a]);if(a&&this.w){for(var b=j,d=this.w.length-1;0<=d;d--)if(this.w[d]===a){b=f;this.w.splice(d,1);break}b&&(this.xa[a.id]=h,this.H[a.name]=h,(b=a.k())&&b.parentNode===this.a&&this.a.removeChild(a.k()))}};n.s=m("");n.d=function(a,b){u.d(this.a,a,u.bind(this,b));return this};n.n=function(a,b){u.n(this.a,a,b);return this};n.F=function(a,b){u.F(this.a,a,u.bind(this,b));return this};n.i=function(a,b){u.i(this.a,a,b);return this};
function y(a,b){b&&(a.R?b.call(a):(a.qa===c&&(a.qa=[]),a.qa.push(b)))}function ha(a){a.R=f;var b=a.qa;if(b&&0<b.length){for(var d=0,e=b.length;d<e;d++)b[d].call(a);a.qa=[];a.i("ready")}}n.p=function(a){u.p(this.a,a);return this};n.v=function(a){u.v(this.a,a);return this};n.show=function(){this.a.style.display="block";return this};n.m=function(){this.a.style.display="none";return this};n.ea=function(){this.v("vjs-fade-out");this.p("vjs-fade-in");return this};
n.Aa=function(){this.v("vjs-fade-in");this.p("vjs-fade-out");return this};n.hb=function(){var a=this.a.style;a.display="block";a.opacity=1;a.fc="visible";return this};function ia(a){a=a.a.style;a.display="";a.opacity="";a.fc=""}n.width=function(a,b){return ja(this,"width",a,b)};n.height=function(a,b){return ja(this,"height",a,b)};n.Db=function(a,b){return this.width(a,f).height(b)};
function ja(a,b,d,e){if(d!==c)return a.a.style[b]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:d+"px",e||a.i("resize"),a;if(!a.a)return 0;d=a.a.style[b];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+u.L(b)],10)}
function v(a,b,d){this.G=a;b=u.g.u(ka(a),b);this.l={};this.jb=b.poster;this.Wa=b.controls;x.call(this,this,b,d);this.F("play",function(a){u.i(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.d("ended",this.Nb);this.d("play",this.Na);this.d("firstplay",this.Ob);this.d("pause",this.Ma);this.d("progress",this.Qb);this.d("durationchange",this.Mb);this.d("error",this.Ka);this.d("fullscreenchange",this.Pb);u.na[this.C]=this;b.plugins&&
u.g.W(b.plugins,function(a,b){this[a](b)},this)}t(v,x);n=v.prototype;n.f=u.options;n.z=function(){u.na[this.C]=h;this.G&&this.G.player&&(this.G.player=h);this.a&&this.a.player&&(this.a.player=h);clearInterval(this.pa);this.Z();this.h&&this.h.z();v.e.z.call(this)};
function ka(a){var b={sources:[],tracks:[]};u.g.u(b,u.Ca(a));if(a.hasChildNodes())for(var d,e=a.childNodes,g=0,p=e.length;g<p;g++)a=e[g],d=a.nodeName.toLowerCase(),"source"===d?b.sources.push(u.Ca(a)):"track"===d&&b.tracks.push(u.Ca(a));return b}
n.c=function(){var a=this.a=v.e.c.call(this,"div"),b=this.G;b.removeAttribute("controls");b.removeAttribute("poster");b.removeAttribute("width");b.removeAttribute("height");if(b.hasChildNodes())for(var d=b.childNodes.length,e=0,g=b.childNodes;e<d;e++)("source"==g[0].nodeName.toLowerCase()||"track"==g[0].nodeName.toLowerCase())&&b.removeChild(g[0]);b.id=b.id||"vjs_video_"+u.o++;a.id=b.id;a.className=b.className;b.id+="_html5_api";b.className="vjs-tech";b.player=a.player=this;this.p("vjs-paused");this.width(this.f.width,
f);this.height(this.f.height,f);b.parentNode&&b.parentNode.insertBefore(a,b);u.Ea(b,a);return a};
function la(a,b,d){a.h?ma(a):"Html5"!==b&&a.G&&(a.a.removeChild(a.G),a.G=h);a.N=b;a.R=j;var e=u.g.u({source:d,parentEl:a.a},a.f[b.toLowerCase()]);d&&(d.src==a.l.src&&0<a.l.currentTime&&(e.startTime=a.l.currentTime),a.l.src=d.src);a.h=new window.videojs[b](a,e);y(a.h,function(){ha(this.b);if(!this.t.kb){var a=this.b;a.Ia=f;a.pa=setInterval(u.bind(a,function(){this.l.wa<this.buffered().end(0)?this.i("progress"):1==na(this)&&(clearInterval(this.pa),this.i("progress"))}),500);a.h.F("progress",function(){this.t.kb=
f;var a=this.b;a.Ia=j;clearInterval(a.pa)})}this.t.pb||(a=this.b,a.Ja=f,a.d("play",a.qb),a.d("pause",a.Z),a.h.F("timeupdate",function(){this.t.pb=f;oa(this.b)}))})}function ma(a){a.h.z();a.Ia&&(a.Ia=j,clearInterval(a.pa));a.Ja&&oa(a);a.h=j}function oa(a){a.Ja=j;a.Z();a.n("play",a.qb);a.n("pause",a.Z)}n.qb=function(){this.Za&&this.Z();this.Za=setInterval(u.bind(this,function(){this.i("timeupdate")}),250)};n.Z=function(){clearInterval(this.Za)};n.Nb=function(){this.f.loop&&(this.currentTime(0),this.play())};
n.Na=function(){u.v(this.a,"vjs-paused");u.p(this.a,"vjs-playing")};n.Ob=function(){this.f.starttime&&this.currentTime(this.f.starttime)};n.Ma=function(){u.v(this.a,"vjs-playing");u.p(this.a,"vjs-paused")};n.Qb=function(){1==na(this)&&this.i("loadedalldata")};n.Mb=function(){this.duration(z(this,"duration"))};n.Ka=function(a){u.log("Video Error",a)};n.Pb=function(){this.D?this.p("vjs-fullscreen"):this.v("vjs-fullscreen")};
function A(a,b,d){if(a.h&&a.h.R)y(a.h,function(){this[b](d)});else try{a.h[b](d)}catch(e){u.log(e)}}function z(a,b){if(a.h.R)try{return a.h[b]()}catch(d){if(a.h[b]===c)u.log("Video.js: "+b+" method not defined for "+a.N+" playback technology.",d);else{if("TypeError"==d.name)throw u.log("Video.js: "+b+" unavailable on "+a.N+" playback technology element.",d),a.h.R=j,d;u.log(d)}}}n.play=function(){var a={type:"play",target:this.a};this.i(a);a.ga()||A(this,"play");return this};
n.pause=function(){A(this,"pause");return this};n.paused=function(){return z(this,"paused")===j?j:f};n.currentTime=function(a){return a!==c?(this.l.qc=a,A(this,"setCurrentTime",a),this.Ja&&this.i("timeupdate"),this):this.l.currentTime=z(this,"currentTime")||0};n.duration=function(a){return a!==c?(this.l.duration=parseFloat(a),this):this.l.duration};n.buffered=function(){var a=z(this,"buffered"),b=this.l.wa=this.l.wa||0;a&&(0<a.length&&a.end(0)!==b)&&(b=a.end(0),this.l.wa=b);return u.Ya(b)};
function na(a){return a.duration()?a.buffered().end(0)/a.duration():0}n.volume=function(a){if(a!==c)return a=Math.max(0,Math.min(1,parseFloat(a))),this.l.volume=a,A(this,"setVolume",a),u.Yb(a),this;a=parseFloat(z(this,"volume"));return isNaN(a)?1:a};n.muted=function(a){return a!==c?(A(this,"setMuted",a),this):z(this,"muted")||j};n.sa=function(){return z(this,"supportsFullScreen")||j};
n.ra=function(){var a=u.Qa.ra;this.D=f;a?(u.d(document,a.Q,u.bind(this,function(){this.D=document[a.D];this.D===j&&u.n(document,a.Q,arguments.callee);this.i("fullscreenchange")})),this.h.t.cb===j&&this.f.flash.iFrameMode!==f&&(this.pause(),ma(this),u.d(document,a.Q,u.bind(this,function(){u.n(document,a.Q,arguments.callee);la(this,this.N,{src:this.l.src})}))),this.a[a.Ub]()):this.h.sa()?(this.i("fullscreenchange"),A(this,"enterFullScreen")):(this.i("fullscreenchange"),this.Ib=f,this.Eb=document.documentElement.style.overflow,
u.d(document,"keydown",u.bind(this,this.bb)),document.documentElement.style.overflow="hidden",u.p(document.body,"vjs-full-window"),u.p(this.a,"vjs-fullscreen"),this.i("enterFullWindow"));return this};function pa(a){var b=u.Qa.ra;a.D=j;b?(a.h.t.cb===j&&a.f.flash.iFrameMode!==f&&(a.pause(),ma(a),u.d(document,b.Q,u.bind(a,function(){u.n(document,b.Q,arguments.callee);la(this,this.N,{src:this.l.src})}))),document[b.Bb]()):(a.h.sa()?A(a,"exitFullScreen"):qa(a),a.i("fullscreenchange"))}
n.bb=function(a){27===a.keyCode&&(this.D===f?pa(this):qa(this))};function qa(a){a.Ib=j;u.n(document,"keydown",a.bb);document.documentElement.style.overflow=a.Eb;u.v(document.body,"vjs-full-window");u.v(a.a,"vjs-fullscreen");a.i("exitFullWindow")}
n.src=function(a){if(a instanceof Array){var b;a:{b=a;for(var d=0,e=this.f.techOrder;d<e.length;d++){var g=u.L(e[d]),p=window.videojs[g];if(p.isSupported())for(var l=0,s=b;l<s.length;l++){var q=s[l];if(p.canPlaySource(q)){b={source:q,h:g};break a}}}b=j}b?(a=b.source,b=b.h,b==this.N?this.src(a):la(this,b,a)):this.a.appendChild(u.c("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://www.google.com/chrome">Google Chrome</a> or download the latest <a href="http://get.adobe.com/flashplayer/">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.N].canPlaySource(a)?this.src(a.src):this.src([a]):(this.l.src=a,this.R?(A(this,"src",a),"auto"==this.f.preload&&this.load(),this.f.autoplay&&this.play()):y(this,function(){this.src(a)}));return this};n.load=function(){A(this,"load");return this};n.currentSrc=function(){return z(this,"currentSrc")||this.l.src||""};n.oa=function(a){return a!==c?(A(this,"setPreload",a),this.f.preload=a,this):z(this,"preload")};
n.autoplay=function(a){return a!==c?(A(this,"setAutoplay",a),this.f.autoplay=a,this):z(this,"autoplay")};n.loop=function(a){return a!==c?(A(this,"setLoop",a),this.f.loop=a,this):z(this,"loop")};n.poster=function(a){a!==c&&(this.jb=a);return this.jb};n.controls=function(a){a!==c&&(this.Wa=a);return this.Wa};n.error=function(){return z(this,"error")};var ra,sa,ta,ua;
if(document.lc!==c)ra="requestFullscreen",sa="exitFullscreen",ta="fullscreenchange",ua="fullScreen";else for(var va=["moz","webkit"],wa=va.length-1;0<=wa;wa--){var B=va[wa];if(("moz"!=B||document.mozFullScreenEnabled)&&document[B+"CancelFullScreen"]!==c)ra=B+"RequestFullScreen",sa=B+"CancelFullScreen",ta=B+"fullscreenchange",ua="webkit"==B?B+"IsFullScreen":B+"FullScreen"}ra&&(u.Qa.ra={Ub:ra,Bb:sa,Q:ta,D:ua});
function xa(a,b,d){x.call(this,a,b,d);if(!a.f.sources||0===a.f.sources.length){b=0;for(d=a.f.techOrder;b<d.length;b++){var e=u.L(d[b]),g=window.videojs[e];if(g&&g.isSupported()){la(a,e);break}}}else a.src(a.f.sources)}t(xa,x);function C(a,b){x.call(this,a,b)}t(C,x);C.prototype.s=function(){return"vjs-control "+C.e.s.call(this)};function D(a,b){x.call(this,a,b);a.F("play",u.bind(this,function(){this.ea();this.b.d("mouseover",u.bind(this,this.ea));this.b.d("mouseout",u.bind(this,this.Aa))}))}t(D,x);
n=D.prototype;n.f={rc:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};n.c=function(){return u.c("div",{className:"vjs-control-bar"})};n.ea=function(){D.e.ea.call(this);this.b.i("controlsvisible")};n.Aa=function(){D.e.Aa.call(this);this.b.i("controlshidden")};n.hb=function(){this.a.style.opacity="1"};
function E(a,b){x.call(this,a,b);this.d("click",this.j);this.d("focus",this.ka);this.d("blur",this.ja)}t(E,C);n=E.prototype;n.c=function(a,b){b=u.g.u({className:this.s(),innerHTML:'<div><span class="vjs-control-text">'+(this.K||"Need Text")+"</span></div>",Vb:"button","aria-live":"polite",tabIndex:0},b);return E.e.c.call(this,a,b)};n.j=function(){};n.ka=function(){u.d(document,"keyup",u.bind(this,this.M))};n.M=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.j()};
n.ja=function(){u.n(document,"keyup",u.bind(this,this.M))};function F(a,b){E.call(this,a,b)}t(F,E);F.prototype.K="Play";F.prototype.s=function(){return"vjs-play-button "+F.e.s.call(this)};F.prototype.j=function(){this.b.play()};function G(a,b){E.call(this,a,b)}t(G,E);G.prototype.K="Play";G.prototype.s=function(){return"vjs-pause-button "+G.e.s.call(this)};G.prototype.j=function(){this.b.pause()};function ya(a,b){E.call(this,a,b);a.d("play",u.bind(this,this.Na));a.d("pause",u.bind(this,this.Ma))}
t(ya,E);n=ya.prototype;n.K="Play";n.s=function(){return"vjs-play-control "+ya.e.s.call(this)};n.j=function(){this.b.paused()?this.b.play():this.b.pause()};n.Na=function(){u.v(this.a,"vjs-paused");u.p(this.a,"vjs-playing");this.a.children[0].children[0].innerHTML="Pause"};n.Ma=function(){u.v(this.a,"vjs-playing");u.p(this.a,"vjs-paused");this.a.children[0].children[0].innerHTML="Play"};function H(a,b){E.call(this,a,b)}t(H,E);H.prototype.K="Fullscreen";
H.prototype.s=function(){return"vjs-fullscreen-control "+H.e.s.call(this)};H.prototype.j=function(){this.b.D?(pa(this.b),this.a.children[0].children[0].innerHTML="Fullscreen"):(this.b.ra(),this.a.children[0].children[0].innerHTML="Non-Fullscreen")};function I(a,b){E.call(this,a,b);a.d("play",u.bind(this,this.m))}t(I,E);I.prototype.c=function(){return I.e.c.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>","aria-label":"play video"})};
I.prototype.j=function(){this.b.currentTime()&&this.b.currentTime(0);this.b.play()};function J(a,b){x.call(this,a,b);a.d("canplay",u.bind(this,this.m));a.d("canplaythrough",u.bind(this,this.m));a.d("playing",u.bind(this,this.m));a.d("seeked",u.bind(this,this.m));a.d("seeking",u.bind(this,this.show));a.d("seeked",u.bind(this,this.m));a.d("error",u.bind(this,this.show));a.d("waiting",u.bind(this,this.show))}t(J,x);
J.prototype.c=function(){var a,b;"string"==typeof this.b.k().style.WebkitBorderRadius||"string"==typeof this.b.k().style.MozBorderRadius||"string"==typeof this.b.k().style.jc||"string"==typeof this.b.k().style.kc?(a="vjs-loading-spinner",b='<div class="ball1"></div><div class="ball2"></div><div class="ball3"></div><div class="ball4"></div><div class="ball5"></div><div class="ball6"></div><div class="ball7"></div><div class="ball8"></div>'):(a="vjs-loading-spinner-fallback",b="");return J.e.c.call(this,
"div",{className:a,innerHTML:b})};function K(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.ba))}t(K,x);K.prototype.c=function(){var a=K.e.c.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(u.c("div").appendChild(this.content));return a};
K.prototype.ba=function(){var a=this.b.Pa?this.b.l.currentTime:this.b.currentTime();this.content.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.fa(a,this.b.duration())};function L(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.ba))}t(L,x);
L.prototype.c=function(){var a=L.e.c.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>-0:00',"aria-live":"off"});a.appendChild(u.c("div").appendChild(this.content));return a};L.prototype.ba=function(){this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Duration Time </span>-'+u.fa(this.b.duration()))};
function za(a,b){x.call(this,a,b)}t(za,x);za.prototype.c=function(){return za.e.c.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};function M(a,b){x.call(this,a,b);a.d("timeupdate",u.bind(this,this.ba))}t(M,x);
M.prototype.c=function(){var a=M.e.c.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.c("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(u.c("div").appendChild(this.content));return a};
M.prototype.ba=function(){this.b.duration()&&this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.fa(this.b.duration()-this.b.currentTime()))};function N(a,b){x.call(this,a,b);this.zb=this.H[this.f.barName];this.handle=this.H[this.f.handleName];a.d(this.ib,u.bind(this,this.update));this.d("mousedown",this.La);this.d("focus",this.ka);this.d("blur",this.ja);this.b.d("controlsvisible",u.bind(this,this.update));y(a,u.bind(this,this.update))}t(N,x);n=N.prototype;
n.c=function(a,b){b=u.g.u({Vb:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},b);return N.e.c.call(this,a,b)};n.La=function(a){a.preventDefault();u.Ab();u.d(document,"mousemove",u.bind(this,this.la));u.d(document,"mouseup",u.bind(this,this.ma));this.la(a)};n.ma=function(){u.dc();u.n(document,"mousemove",this.la,j);u.n(document,"mouseup",this.ma,j);this.update()};
n.update=function(){if(this.a){var a,b=this.Da(),d=this.handle,e=this.zb;isNaN(b)&&(b=0);a=b;if(d){a=this.a.offsetWidth;var g=d.k().offsetWidth;a=g?g/a:0;b*=1-a;a=b+a/2;d.k().style.left=u.round(100*b,2)+"%"}e.k().style.width=u.round(100*a,2)+"%"}};function Aa(a,b){var d=a.a,e=u.Gb(d),d=d.offsetWidth,g=a.handle;g&&(g=g.k().offsetWidth,e+=g/2,d-=g);return Math.max(0,Math.min(1,(b.pageX-e)/d))}n.ka=function(){u.d(document,"keyup",u.bind(this,this.M))};
n.M=function(a){37==a.which?(a.preventDefault(),this.nb()):39==a.which&&(a.preventDefault(),this.ob())};n.ja=function(){u.n(document,"keyup",u.bind(this,this.M))};function O(a,b){x.call(this,a,b)}t(O,x);O.prototype.f={children:{seekBar:{}}};O.prototype.c=function(){return O.e.c.call(this,"div",{className:"vjs-progress-control vjs-control"})};function P(a,b){N.call(this,a,b);a.d("timeupdate",u.bind(this,this.aa));y(a,u.bind(this,this.aa))}t(P,N);n=P.prototype;
n.f={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};n.ib="timeupdate";n.c=function(){return P.e.c.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};n.aa=function(){var a=this.b.Pa?this.b.l.currentTime:this.b.currentTime();this.a.setAttribute("aria-valuenow",u.round(100*this.Da(),2));this.a.setAttribute("aria-valuetext",u.fa(a,this.b.duration()))};n.Da=function(){return this.b.currentTime()/this.b.duration()};
n.La=function(a){P.e.La.call(this,a);this.b.Pa=f;this.ec=!this.b.paused();this.b.pause()};n.la=function(a){a=Aa(this,a)*this.b.duration();a==this.b.duration()&&(a-=0.1);this.b.currentTime(a)};n.ma=function(a){P.e.ma.call(this,a);this.b.Pa=j;this.ec&&this.b.play()};n.ob=function(){this.b.currentTime(this.b.currentTime()+5)};n.nb=function(){this.b.currentTime(this.b.currentTime()-5)};function Ba(a,b){x.call(this,a,b);a.d("progress",u.bind(this,this.update))}t(Ba,x);
Ba.prototype.c=function(){return Ba.e.c.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};Ba.prototype.update=function(){this.a.style&&(this.a.style.width=u.round(100*na(this.b),2)+"%")};function Ca(a,b){x.call(this,a,b)}t(Ca,x);Ca.prototype.c=function(){return Ca.e.c.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};function Da(a,b){x.call(this,a,b)}t(Da,x);
Da.prototype.c=function(){return Da.e.c.call(this,"div",{className:"vjs-seek-handle",innerHTML:'<span class="vjs-control-text">00:00</span>'})};function Ea(a,b){x.call(this,a,b);a.h&&a.h.t.ta===j&&this.m();a.d("loadstart",u.bind(this,function(){a.h.t.ta===j?this.m():this.show()}))}t(Ea,x);Ea.prototype.f={children:{volumeBar:{}}};Ea.prototype.c=function(){return Ea.e.c.call(this,"div",{className:"vjs-volume-control vjs-control"})};
function Fa(a,b){N.call(this,a,b);a.d("volumechange",u.bind(this,this.aa));y(a,u.bind(this,this.aa));setTimeout(u.bind(this,this.update),0)}t(Fa,N);n=Fa.prototype;n.aa=function(){this.a.setAttribute("aria-valuenow",u.round(100*this.b.volume(),2));this.a.setAttribute("aria-valuetext",u.round(100*this.b.volume(),2)+"%")};n.f={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};n.ib="volumechange";
n.c=function(){return Fa.e.c.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};n.la=function(a){this.b.volume(Aa(this,a))};n.Da=function(){return this.b.volume()};n.ob=function(){this.b.volume(this.b.volume()+0.1)};n.nb=function(){this.b.volume(this.b.volume()-0.1)};function Ga(a,b){x.call(this,a,b)}t(Ga,x);Ga.prototype.c=function(){return Ga.e.c.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};
function Ha(a,b){x.call(this,a,b)}t(Ha,x);Ha.prototype.c=function(){return Ha.e.c.call(this,"div",{className:"vjs-volume-handle",innerHTML:'<span class="vjs-control-text"></span>'})};function Q(a,b){E.call(this,a,b);a.d("volumechange",u.bind(this,this.update));a.h&&a.h.t.ta===j&&this.m();a.d("loadstart",u.bind(this,function(){a.h.t.ta===j?this.m():this.show()}))}t(Q,E);Q.prototype.c=function(){return Q.e.c.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};
Q.prototype.j=function(){this.b.muted(this.b.muted()?j:f)};Q.prototype.update=function(){var a=this.b.volume(),b=3;0===a||this.b.muted()?b=0:0.33>a?b=1:0.67>a&&(b=2);this.b.muted()?"Unmute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.v(this.a,"vjs-vol-"+a);u.p(this.a,"vjs-vol-"+b)};
function Ia(a,b){E.call(this,a,b);a.poster()||this.m();a.d("play",u.bind(this,this.m))}t(Ia,E);Ia.prototype.c=function(){var a=u.c("div",{className:"vjs-poster",tabIndex:-1}),b=this.b.poster();b&&("backgroundSize"in a.style?a.style.backgroundImage='url("'+b+'")':a.appendChild(u.c("img",{src:b})));return a};Ia.prototype.j=function(){this.b.play()};function R(a,b){x.call(this,a,b)}t(R,x);function Ja(a,b){a.J(b);b.d("click",u.bind(a,function(){ia(this)}))}
R.prototype.c=function(){return R.e.c.call(this,"ul",{className:"vjs-menu"})};function S(a,b){E.call(this,a,b);b.selected?(this.p("vjs-selected"),this.a.setAttribute("aria-selected",f)):this.a.setAttribute("aria-selected",j)}t(S,E);S.prototype.c=function(a,b){return S.e.c.call(this,"li",u.g.u({className:"vjs-menu-item",innerHTML:this.f.label},b))};S.prototype.j=function(){this.selected(f)};
S.prototype.selected=function(a){a?(this.p("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.v("vjs-selected"),this.a.setAttribute("aria-selected",j))};function T(a,b,d){x.call(this,a,b,d)}t(T,x);T.prototype.j=function(){this.b.controls()&&(this.b.paused()?this.b.play():this.b.pause())};u.media={};u.media.ua="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function Ka(){var a=u.media.ua[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.ua.length-1;0<=i;i--)T.prototype[u.media.ua[i]]=Ka();
function U(a,b,d){x.call(this,a,b,d);(b=b.source)&&this.a.currentSrc==b.src?a.i("loadstart"):b&&(this.a.src=b.src);y(a,function(){this.f.autoplay&&this.paused()&&(this.G.poster=h,this.play())});this.d("click",this.j);for(a=La.length-1;0<=a;a--)u.d(this.a,La[a],u.bind(this.b,this.Fb));ha(this)}t(U,T);n=U.prototype;n.z=function(){U.e.z.call(this)};
n.c=function(){var a=this.b,b=a.G;if(!b||this.t.Kb===j)b?(a.k().removeChild(b),b=b.cloneNode(j)):b=u.c("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),b.player=a,u.Ea(b,a.k());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.f[g]!==h&&(b[g]=a.f[g])}return b};n.Fb=function(a){"play"!==a.type&&(this.i(a),a.stopPropagation())};n.play=function(){this.a.play()};n.pause=function(){this.a.pause()};n.paused=function(){return this.a.paused};n.currentTime=function(){return this.a.currentTime};
n.Xb=function(a){try{this.a.currentTime=a}catch(b){u.log(b,"Video is not ready. (Video.js)")}};n.duration=function(){return this.a.duration||0};n.buffered=function(){return this.a.buffered};n.volume=function(){return this.a.volume};n.bc=function(a){this.a.volume=a};n.muted=function(){return this.a.muted};n.$b=function(a){this.a.muted=a};n.width=function(){return this.a.offsetWidth};n.height=function(){return this.a.offsetHeight};
n.sa=function(){return"function"==typeof this.a.webkitEnterFullScreen&&!navigator.userAgent.match("Chrome")&&!navigator.userAgent.match("Mac OS X 10.5")?f:j};n.src=function(a){this.a.src=a};n.load=function(){this.a.load()};n.currentSrc=function(){return this.a.currentSrc};n.oa=function(){return this.a.oa};n.ac=function(a){this.a.oa=a};n.autoplay=function(){return this.a.autoplay};n.Wb=function(a){this.a.autoplay=a};n.loop=function(){return this.a.loop};n.Zb=function(a){this.a.loop=a};n.error=function(){return this.a.error};
var La="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" "),Ma=U.prototype,Na=u.ca.webkitEnterFullScreen?!u.B.match("Chrome")&&!u.B.match("Mac OS X 10.5")?f:j:j,Oa=!u.ub,Pa=u.ca.volume;u.ca.volume=Pa/2+0.1;Ma.t={nc:Na,Kb:Oa,ta:Pa!==u.ca.volume};
u.sb&&3>u.rb&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});
function V(a,b,d){x.call(this,a,b,d);var e=b.source,g=b.parentEl;d=this.a=u.c("div",{id:a.id()+"_temp_flash"});var p=a.id()+"_flash_api";a=a.f;var l=u.g.u({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.oa,loop:a.loop,muted:a.muted},b.flashVars),s=u.g.u({wmode:"opaque",bgcolor:"#000000"},b.params),q=u.g.u({id:p,name:p,"class":"vjs-tech"},b.attributes);e&&(l.src=encodeURIComponent(u.eb(e.src)));
u.Ea(d,g);b.startTime&&y(this,function(){this.load();this.play();this.currentTime(b.startTime)});if(b.iFrameMode===f&&!u.tb){var w=u.c("iframe",{id:p+"_iframe",name:p+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});l.readyFunction="ready";l.eventProxyFunction="events";l.errorEventProxyFunction="errors";u.d(w,"load",u.bind(this,function(){var a,d=w.contentWindow;a=w.contentDocument?w.contentDocument:w.contentWindow.document;a.write(Qa(b.swf,l,s,q));d.player=
this.b;d.ready=u.bind(this.b,function(b){b=a.getElementById(b);var d=this.h;d.a=b;u.d(b,"click",d.bind(d.j));Ra(d)});d.events=u.bind(this.b,function(a,b){this&&"flash"===this.N&&this.i(b)});d.errors=u.bind(this.b,function(a,b){u.log("Flash Error",b)})}));d.parentNode.replaceChild(w,d)}else{a=Qa(b.swf,l,s,q);a=u.c("div",{innerHTML:a}).childNodes[0];e=d.parentNode;d.parentNode.replaceChild(a,d);var kb=e.childNodes[0];setTimeout(function(){kb.style.display="block"},1E3)}}t(V,T);n=V.prototype;n.z=function(){V.e.z.call(this)};
n.play=function(){this.a.vjs_play()};n.pause=function(){this.a.vjs_pause()};n.src=function(a){a=u.eb(a);this.a.vjs_src(a);if(this.b.autoplay()){var b=this;setTimeout(function(){b.play()},0)}};n.load=function(){this.a.vjs_load()};n.poster=function(){this.a.vjs_getProperty("poster")};n.buffered=function(){return u.Ya(this.a.vjs_getProperty("buffered"))};n.sa=m(j);
var Sa=V.prototype,Ta="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),Ua="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function Va(){var a=Ta[W],b=a.charAt(0).toUpperCase()+a.slice(1);Sa["set"+b]=function(b){return this.a.vjs_setProperty(a,b)}}
function Wa(a){Sa[a]=function(){return this.a.vjs_getProperty(a)}}var W;for(W=0;W<Ta.length;W++)Wa(Ta[W]),Va();for(W=0;W<Ua.length;W++)Wa(Ua[W]);V.prototype.t={Hb:{"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"},kb:j,pb:j,cb:j,sc:!u.B.match("Firefox")};V.onReady=function(a){a=u.k(a);var b=a.player||a.parentNode.player,d=b.h;a.player=b;d.a=a;d.d("click",d.j);Ra(d)};function Ra(a){a.k().vjs_getProperty?ha(a):setTimeout(function(){Ra(a)},50)}
V.onEvent=function(a,b){"play"!==b&&u.k(a).player.i(b)};V.onError=function(a,b){u.k(a).player.i("error");u.log("Flash Error",b,a)};
function Qa(a,b,d,e){var g="",p="",l="";b&&u.g.W(b,function(a,b){g+=a+"="+b+"&amp;"});d=u.g.u({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.g.W(d,function(a,b){p+='<param name="'+a+'" value="'+b+'" />'});e=u.g.u({data:a,width:"100%",height:"100%"},e);u.g.W(e,function(a,b){l+=a+'="'+b+'" '});return'<object type="application/x-shockwave-flash"'+l+">"+p+"</object>"}function X(a){a.$=a.$||[];return a.$}
function Xa(a,b,d){for(var e=a.$,g=0,p=e.length,l,s;g<p;g++)l=e[g],l.id()===b?(l.show(),s=l):d&&(l.A()==d&&0<l.mode())&&l.disable();(b=s?s.A():d?d:j)&&a.i(b+"trackchange")}function Y(a,b){x.call(this,a,b);this.C=b.id||"vjs_"+b.kind+"_"+b.language+"_"+u.o++;this.mb=b.src;this.Cb=b["default"]||b.dflt;this.uc=b.title;this.pc=b.srclang;this.Jb=b.label;this.P=[];this.Ta=[];this.S=this.T=0;this.b.d("fullscreenchange",u.bind(this,this.yb))}t(Y,x);n=Y.prototype;n.A=k("r");n.src=k("mb");n.za=k("Cb");
n.label=k("Jb");n.readyState=k("T");n.mode=k("S");n.yb=function(){this.a.style.fontSize=this.b.D?140*(screen.width/this.b.width())+"%":""};n.c=function(){return Y.e.c.call(this,"div",{className:"vjs-"+this.r+" vjs-text-track"})};n.show=function(){Ya(this);this.S=2;Y.e.show.call(this)};n.m=function(){Ya(this);this.S=1;Y.e.m.call(this)};
n.disable=function(){2==this.S&&this.m();this.b.n("timeupdate",u.bind(this,this.update,this.C));this.b.n("ended",u.bind(this,this.reset,this.C));this.reset();this.b.H.textTrackDisplay.removeChild(this);this.S=0};function Ya(a){0===a.T&&a.load();0===a.S&&(a.b.d("timeupdate",u.bind(a,a.update,a.C)),a.b.d("ended",u.bind(a,a.reset,a.C)),("captions"===a.r||"subtitles"===a.r)&&a.b.H.textTrackDisplay.J(a))}n.load=function(){0===this.T&&(this.T=1,u.get(this.mb,u.bind(this,this.Rb),u.bind(this,this.Ka)))};
n.Ka=function(a){this.error=a;this.T=3;this.i("error")};n.Rb=function(a){var b,d;a=a.split("\n");for(var e="",g=1,p=a.length;g<p;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(b=e,e=u.trim(a[++g])):b=this.P.length;b={id:b,index:this.P.length};d=e.split(" --\x3e ");b.startTime=Za(d[0]);b.X=Za(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);b.text=d.join("<br/>");this.P.push(b)}this.T=2;this.i("loaded")};
function Za(a){var b=a.split(":");a=0;var d,e,g;3==b.length?(d=b[0],e=b[1],b=b[2]):(d=0,e=b[0],b=b[1]);b=b.split(/\s+/);b=b.splice(0,1)[0];b=b.split(/\.|,/);g=parseFloat(b[1]);b=b[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(b);g&&(a+=g/1E3);return a}
n.update=function(){if(0<this.P.length){var a=this.b.currentTime();if(this.Oa===c||a<this.Oa||this.ia<=a){var b=this.P,d=this.b.duration(),e=0,g=j,p=[],l,s,q,w;a>=this.ia||this.ia===c?w=this.Ba!==c?this.Ba:0:(g=f,w=this.Ha!==c?this.Ha:b.length-1);for(;;){q=b[w];if(q.X<=a)e=Math.max(e,q.X),q.da&&(q.da=j);else if(a<q.startTime){if(d=Math.min(d,q.startTime),q.da&&(q.da=j),!g)break}else g?(p.splice(0,0,q),s===c&&(s=w),l=w):(p.push(q),l===c&&(l=w),s=w),d=Math.min(d,q.X),e=Math.max(e,q.startTime),q.da=
f;if(g)if(0===w)break;else w--;else if(w===b.length-1)break;else w++}this.Ta=p;this.ia=d;this.Oa=e;this.Ba=l;this.Ha=s;a=this.Ta;b="";d=0;for(e=a.length;d<e;d++)b+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.a.innerHTML=b;this.i("cuechange")}}};n.reset=function(){this.ia=0;this.Oa=this.b.duration();this.Ha=this.Ba=0};function $a(a,b){Y.call(this,a,b)}t($a,Y);$a.prototype.r="captions";function ab(a,b){Y.call(this,a,b)}t(ab,Y);ab.prototype.r="subtitles";function bb(a,b){Y.call(this,a,b)}
t(bb,Y);bb.prototype.r="chapters";function cb(a,b,d){x.call(this,a,b,d);if(a.f.tracks&&0<a.f.tracks.length){b=this.b;a=a.f.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=b,p=e.kind,l=e.label,s=e.language,q=e;e=g.$=g.$||[];q=q||{};q.kind=p;q.label=l;q.language=s;p=u.L(p||"subtitles");g=new window.videojs[p+"Track"](g,q);e.push(g)}}}t(cb,x);cb.prototype.c=function(){return cb.e.c.call(this,"div",{className:"vjs-text-track-display"})};
function Z(a,b){var d=this.O=b.track;b.label=d.label();b.selected=d.za();S.call(this,a,b);this.b.d(d.A()+"trackchange",u.bind(this,this.update))}t(Z,S);Z.prototype.j=function(){Z.e.j.call(this);Xa(this.b,this.O.C,this.O.A())};Z.prototype.update=function(){2==this.O.mode()?this.selected(f):this.selected(j)};function db(a,b){b.track={A:function(){return b.kind},Sb:a,label:m("Off"),za:m(j),mode:m(j)};Z.call(this,a,b)}t(db,Z);db.prototype.j=function(){db.e.j.call(this);Xa(this.b,this.O.C,this.O.A())};
db.prototype.update=function(){for(var a=X(this.b),b=0,d=a.length,e,g=f;b<d;b++)e=a[b],e.A()==this.O.A()&&2==e.mode()&&(g=j);g?this.selected(f):this.selected(j)};function $(a,b){E.call(this,a,b);this.ha=this.ya();0===this.Y.length&&this.m();this.d("keyup",this.M);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}t($,E);n=$.prototype;n.U=j;
n.ya=function(){var a=new R(this.b);a.k().appendChild(u.c("li",{className:"vjs-menu-title",innerHTML:u.L(this.r),cc:-1}));Ja(a,new db(this.b,{kind:this.r}));this.Y=this.Xa();for(var b=0;b<this.Y.length;b++)Ja(a,this.Y[b]);this.J(a);return a};n.Xa=function(){for(var a=[],b,d=0;d<X(this.b).length;d++)b=X(this.b)[d],b.A()===this.r&&a.push(new Z(this.b,{track:b}));return a};n.s=function(){return this.className+" vjs-menu-button "+$.e.s.call(this)};n.ka=function(){};n.ja=function(){};
n.j=function(){this.F("mouseout",u.bind(this,function(){ia(this.ha);this.a.blur()}));this.U?eb(this):fb(this)};n.M=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.U?eb(this):fb(this);27==a.which&&(a.preventDefault(),this.U&&eb(this))};function fb(a){a.U=f;a.ha.hb();a.a.setAttribute("aria-pressed",f);a.a.children[1].children[0].focus()}function eb(a){a.U=j;ia(a.ha);a.a.setAttribute("aria-pressed",j)}
function gb(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Captions Menu")}t(gb,$);gb.prototype.r="captions";gb.prototype.K="Captions";gb.prototype.className="vjs-captions-button";function hb(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Subtitles Menu")}t(hb,$);hb.prototype.r="subtitles";hb.prototype.K="Subtitles";hb.prototype.className="vjs-subtitles-button";function ib(a,b){$.call(this,a,b);this.a.setAttribute("aria-label","Chapters Menu")}t(ib,$);n=ib.prototype;n.r="chapters";
n.K="Chapters";n.className="vjs-chapters-button";n.Xa=function(){for(var a=[],b,d=0;d<X(this.b).length;d++)b=X(this.b)[d],b.A()===this.r&&a.push(new Z(this.b,{track:b}));return a};
n.ya=function(){for(var a=X(this.b),b=0,d=a.length,e,g,p=this.Y=[];b<d;b++)if(e=a[b],e.A()==this.r&&e.za()){if(2>e.readyState()){this.mc=e;e.d("loaded",u.bind(this,this.ya));return}g=e;break}a=this.ha=new R(this.b);a.a.appendChild(u.c("li",{className:"vjs-menu-title",innerHTML:u.L(this.r),cc:-1}));if(g){e=g.P;for(var l,b=0,d=e.length;b<d;b++)l=e[b],l=new jb(this.b,{track:g,cue:l}),p.push(l),a.J(l)}this.J(a);0<this.Y.length&&this.show();return a};
function jb(a,b){var d=this.O=b.track,e=this.cue=b.cue,g=a.currentTime();b.label=e.text;b.selected=e.startTime<=g&&g<e.X;S.call(this,a,b);d.d("cuechange",u.bind(this,this.update))}t(jb,S);jb.prototype.j=function(){jb.e.j.call(this);this.b.currentTime(this.cue.startTime);this.update(this.cue.startTime)};jb.prototype.update=function(){var a=this.cue,b=this.b.currentTime();a.startTime<=b&&b<a.X?this.selected(f):this.selected(j)};u.g.u(D.prototype.f.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)u.JSON=window.JSON;else{u.JSON={};var lb=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,b){function d(a,e){var l,s,q=a[e];if(q&&"object"===typeof q)for(l in q)Object.prototype.hasOwnProperty.call(q,l)&&(s=d(q,l),s!==c?q[l]=s:delete q[l]);return b.call(a,e,q)}var e;a=String(a);lb.lastIndex=0;lb.test(a)&&(a=a.replace(lb,function(a){return"\\u"+("0000"+
a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?d({"":e},""):e;throw new SyntaxError("JSON.parse");}}
u.va=function(){var a,b,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((b=d[e])&&b.getAttribute)b.player===c&&(a=b.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),ba(b,a)));else{u.Ua();break}else u.gc||u.Ua()};u.Ua=function(){setTimeout(u.va,1)};u.F(window,"load",function(){u.gc=f});u.va();u.Tb=function(a,b){v.prototype[a]=b};r("videojs",u);r("_V_",u);r("videojs.options",u.options);r("videojs.cache",u.V);r("videojs.Component",x);
x.prototype.dispose=x.prototype.z;x.prototype.createEl=x.prototype.c;x.prototype.el=x.prototype.k;x.prototype.addChild=x.prototype.J;x.prototype.children=x.prototype.children;x.prototype.on=x.prototype.d;x.prototype.off=x.prototype.n;x.prototype.one=x.prototype.F;x.prototype.trigger=x.prototype.i;x.prototype.show=x.prototype.show;x.prototype.hide=x.prototype.m;x.prototype.width=x.prototype.width;x.prototype.height=x.prototype.height;x.prototype.dimensions=x.prototype.Db;r("videojs.Player",v);
r("videojs.MediaLoader",xa);r("videojs.PosterImage",Ia);r("videojs.LoadingSpinner",J);r("videojs.BigPlayButton",I);r("videojs.ControlBar",D);r("videojs.TextTrackDisplay",cb);r("videojs.Control",C);r("videojs.ControlBar",D);r("videojs.Button",E);r("videojs.PlayButton",F);r("videojs.PauseButton",G);r("videojs.PlayToggle",ya);r("videojs.FullscreenToggle",H);r("videojs.BigPlayButton",I);r("videojs.LoadingSpinner",J);r("videojs.CurrentTimeDisplay",K);r("videojs.DurationDisplay",L);
r("videojs.TimeDivider",za);r("videojs.RemainingTimeDisplay",M);r("videojs.Slider",N);r("videojs.ProgressControl",O);r("videojs.SeekBar",P);r("videojs.LoadProgressBar",Ba);r("videojs.PlayProgressBar",Ca);r("videojs.SeekHandle",Da);r("videojs.VolumeControl",Ea);r("videojs.VolumeBar",Fa);r("videojs.VolumeLevel",Ga);r("videojs.VolumeHandle",Ha);r("videojs.MuteToggle",Q);r("videojs.PosterImage",Ia);r("videojs.Menu",R);r("videojs.MenuItem",S);r("videojs.SubtitlesButton",hb);
r("videojs.CaptionsButton",gb);r("videojs.ChaptersButton",ib);r("videojs.MediaTechController",T);r("videojs.Html5",U);U.Events=La;U.isSupported=function(){return!!document.createElement("video").canPlayType};U.canPlaySource=function(a){return!!document.createElement("video").canPlayType(a.type)};U.prototype.setCurrentTime=U.prototype.Xb;U.prototype.setVolume=U.prototype.bc;U.prototype.setMuted=U.prototype.$b;U.prototype.setPreload=U.prototype.ac;U.prototype.setAutoplay=U.prototype.Wb;
U.prototype.setLoop=U.prototype.Zb;r("videojs.Flash",V);V.isSupported=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(b){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return 10<=a.split(",")[0]};
V.canPlaySource=function(a){if(a.type in V.prototype.t.Hb)return"maybe"};V.onReady=V.onReady;r("videojs.TextTrack",Y);Y.prototype.label=Y.prototype.label;r("videojs.CaptionsTrack",$a);r("videojs.SubtitlesTrack",ab);r("videojs.ChaptersTrack",bb);r("videojs.autoSetup",u.va);r("videojs.plugin",u.Tb);
